export { makeMetallicGradient, METALLIC_PEACH_MID } from "./makeMetallicGradient";
export { makeWhiteCardWithStraddlingTitle }          from "./makeWhiteCardWithStraddlingTitle";
export { makeDisplayHeadline }                       from "./makeDisplayHeadline";
export { makeBodyText }                              from "./makeBodyText";
export { makeTiltedPhoneMockup }                     from "./makeTiltedPhoneMockup";
export type { TiltedPhoneMockupOpts }                from "./makeTiltedPhoneMockup";
export { makeTiltedImagePair }                       from "./makeTiltedImagePair";
export { makeItalicCtaLine }                         from "./makeItalicCtaLine";
export { makeOverlayCards }                          from "./makeOverlayCards";
export type { OverlayCardDef }                       from "./makeOverlayCards";
