"""
template_spec_service.py

Loads template content specs from backend/configs/template_content_specs.json.
This JSON is generated by: node scripts/export_specs.cjs

The specs tell the LLM exactly what content each template expects:
  - maxChars / targetChars per text field
  - image requirements (aspect ratio, purpose)
  - contentTone and contentStyle (injected verbatim into the slide generation prompt)
  - exampleContent (reference — not copied verbatim by the LLM)
"""
import json
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

_SPECS_PATH = Path(__file__).parent.parent.parent / "configs" / "template_content_specs.json"


@lru_cache(maxsize=1)
def _load_specs() -> dict:
    """Load and cache the specs JSON. Called once per process lifetime."""
    if not _SPECS_PATH.exists():
        logger.warning(
            "template_content_specs.json not found at %s — "
            "run: node scripts/export_specs.cjs to generate it",
            _SPECS_PATH,
        )
        return {"specs": [], "count": 0}
    try:
        data = json.loads(_SPECS_PATH.read_text())
        logger.info("Loaded %d template content specs", data.get("count", 0))
        return data
    except Exception as e:
        logger.error("Failed to load template_content_specs.json: %s", e)
        return {"specs": [], "count": 0}


def get_all_specs() -> list[dict]:
    """Return all template content specs as a list of dicts."""
    return _load_specs().get("specs", [])


def get_spec(template_id: str) -> dict | None:
    """Return the spec for a given templateId, or None if not found."""
    for spec in get_all_specs():
        if spec.get("templateId") == template_id:
            return spec
    return None


def format_spec_for_prompt(spec: dict) -> str:
    """
    Format a spec as a concise block to inject into the slide generation prompt.
    Tells the LLM exactly how to write content for this template.

    Returns an empty string if spec is None.
    """
    if not spec:
        return ""

    lines = [
        f"TEMPLATE: {spec.get('templateId')} ({spec.get('family')} family, {spec.get('slideRole')} slide)",
        f"TONE: {spec.get('contentTone', '')}",
        f"STYLE: {spec.get('contentStyle', '')}",
        f"EXAMPLE: {spec.get('exampleContent', '')}",
    ]

    text_fields = spec.get("textFields", [])
    if text_fields:
        lines.append("TEXT FIELDS:")
        for tf in text_fields:
            lines.append(
                f"  - {tf.get('label')} [{tf.get('field')}]: "
                f"target {tf.get('targetChars')} chars, max {tf.get('maxChars')} chars. "
                f"Font: {tf.get('font')}."
            )

    images = spec.get("images", [])
    if images:
        lines.append("IMAGES:")
        for img in images:
            req = "REQUIRED" if img.get("required") else "optional"
            lines.append(
                f"  - {tf.get('field', img.get('field'))} ({req}): "
                f"{img.get('aspectRatio')} aspect, {img.get('purpose')}"
            )

    return "\n".join(lines)
